AWSTemplateFormatVersion: "2010-09-09"
Description: "IAM Role for AWS Autograder to validate student lab resources with full read-only access"

Resources:
  AutograderIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "AutograderCheckRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "arn:aws:iam::236921907600:root"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/ReadOnlyAccess"

Outputs:
  RoleARN:
    Description: "ARN of the IAM Role for Autograder"
    Value: !GetAtt AutograderIAMRole.Arn
